### ISSUE TITLE
Nothing is rendering.

### ISSUE THREAD

**Issue by s3w47m88** [riverskies/laravel-mobile-detect#10]
I'm new to Blade, and I'm trying to include your application as a Vendor but the conditions aren't (@desktop, @handheld, @anything).

I followed the readme instructions to add `Riverskies\Laravel\MobileDetect\Facades\MobileDetect::class` to my config file and then placed the sample @desktop conditions in my Blade template. Am I missing a step?

**Comment by barnabaskecskes** [comment]
If your composer install succeeded, that's pretty much all you have to do (for Laravel 5.4 or earlier). So, if you do 
```
@desktop
    <p>Only visible on desktop</p>
@else
    <p>Visible on non-desktop browsers</p>
@enddesktop
```
you should see the first paragraph on desktop browsers. What is that you experience exactly? Nothing showing / wrong content showing / else?

**Comment by andreizakharkin** [comment]
The same problem. @desktop (and other directives) are rendering as simple text.
Laravel 5.5
Tried with and without provider in config/app.php
BUT!
local server - ok
stage server - ok
production server - not ok
php7.1 is on every server

**Comment by barnabaskecskes** [comment]
@andreizakharkin Try clearing your view cache `php artisan view:clear` - that often is required when introducing new Blade directives. Let me know if that worked!

**Comment by s3w47m88** [comment]
In my case, executing artisan commands always returns `Could not open input
file: artisan` - which I understand is because it believes I'm not in the
Laravel Blade directory. Since I'm brand new to Laravel and Blade, and
using it for the first time inside a WordPress Theme (Root's Sage 9) I'm
wondering if they have modified Laravel Blade in some way that would
prevent this command from being run because I can run other Laravel
commands from this directory. Any ideas? @andreizakharkin did this solution
work for you?

**Comment by barnabaskecskes** [comment]
@s3w47m88 what do you mean by 
> I can run other Laravel commands

**Comment by andreizakharkin** [comment]
@barnabaskecskes 
Yes! It was just a view cache :/
Thx
