### ISSUE TITLE
fails while making the website responsive check

### ISSUE THREAD

**Issue by austindudley10** [riverskies/laravel-mobile-detect#12]
First of all thanks for this amazing plugin. It differentiates the mobile view and desktop view very efficiently but when we check using [Chrome’s simulation with google chrome](https://developers.google.com/web/tools/chrome-devtools/device-mode/) and made responsive(custom pixel)such as 1250 * 800, It is showing mobile view whereas it is actually a desktop view. Advance thanks for the feedback. @barnabaskecskes

**Comment by barnabaskecskes** [comment]
@austindudley10 this package uses the `User-Agent` header to determine whether the client is a desktop/tablet/mobile device. When switching to responsive mode in Chrome it sends the original browser headers hence you see the desktop view. If you were to switch the option on the right hand side to imitate a mobile device, the header changes accordingly and you should be able to test your site on any screen size of your choice.

<img width="513" alt="screen shot 2018-09-10 at 07 03 53" src="https://user-images.githubusercontent.com/3535449/45279213-44786580-b4c8-11e8-81c0-0b862c3c38a7.png">

**Comment by austindudley10** [comment]
I tried what you have told me but i got the negative result. It should show "desktop view".
![screenshot from 2018-09-10 12-09-31](https://user-images.githubusercontent.com/43128023/45280775-57ecf600-b4f3-11e8-9fbf-42a9313f582a.png)
These are my code :
 @mobile
Mobile View
@elsemobile
Desktop View
@endmobile

**Comment by barnabaskecskes** [comment]
Ohhh my bad, sorry 😅- as I'm re-reading I see I mixed it up thinking you were after a mobile view and had desktop. OK, so then here is what you can do: 

Switch that option back to 'Online', then go to the far right of that option toolbar and click the 'More options' represented by three vertical dots. Hit 'Add device type' and notice the extra dropdown in the toolbar. Select 'Desktop' and you're done. 😌

**Comment by austindudley10** [comment]
Okay! Thank you :)
