### ISSUE TITLE
Not working in Opera Mini on Android

### ISSUE THREAD

**Issue by wakamin** [riverskies/laravel-mobile-detect#9]
It is not working in Opera Mini. Is there any workaround about this issue? Thanks..

**Comment by wakamin** [comment]
Ah sorry, my mistake. It does works in Opera Mini.
Opera Mini has add blocking feature that makes website displayed ugly.

**Comment by barnabaskecskes** [comment]
Hahaha - that happens. Thanks for letting me know anyway. :)
